name: Script2Grow
favicon: null
layout_spectrum: 0.1181957779917866
typography_spectrum: 0.15884990082122386
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.9897423142101616
  lightness: 0.8906425137538463
  saturation: 0.5161553027573973
  rhythmicContrast: 0.3177308291196823
purpose: []
